#! /usr/bin/python
import logging
import os
import re
import sys

from getopt import GetoptError
from getopt import gnu_getopt
# Add the source directory to the python path so we can use all of the
# cs2mako libs
sys.path[0] = os.path.join(sys.path[0],'src')

from cs2mako.converter import Converter
from cs2mako.addintl import add_intl

def usage():
    """Prints out information detailing how to use cs2mako"""
    print """Usage cs2mako [-o <output_filename>] [--nointl] [--noconv] <cs file>"""

def main():
#    logging.basicConfig(level=logging.DEBUG)
    logging.debug("Starting conversion")
    try:
        opts, args = gnu_getopt(sys.argv[1:], "o:", ["nointl", "noconv"])
    except GetoptError, goe:
        print str(goe)
        usage()
        sys.exit(2)



    output_file = None
    do_intl = True
    do_conv = True
    for o, a in opts:
        if o == '-o':
            output_file = a
            print "Outputfile = %s" % a
        if o == '--nointl':
            do_intl = False
        if o == '--noconv':
            do_conv = False

    if len(args) < 1:
        print "No filename specified."
        usage()
        sys.exit(2)

    cs_data = open(args[0], 'r').read()
    if do_conv:
        converter = Converter(cs_data)
        result = converter.convert()
    else:
        result = cs_data
    if do_intl:
        result = add_intl(result)

    if output_file is not None:
        with open(output_file, "w") as f:
            f.write(result)
    else:
        print result

if __name__ == "__main__":
    main()
